### ISSUE TITLE
TOC(position is not OK)

### ISSUE THREAD

**Issue by sunorry** [borkweb/BootstrapMediaWiki#20]
When I click a title(TOC), the content allways be a little down.
Like this:
 http://eotl.borkweb.com/view/Forester_Guild#Directions
When I click Directions
![image](https://f.cloud.github.com/assets/4231217/1319510/8fd4fdf6-32ee-11e3-8c06-79b2cbc1a2e2.png)
It should be there.
![image](https://f.cloud.github.com/assets/4231217/1319512/acb47ce4-32ee-11e3-8f59-ed26a2558d1d.png)

**Comment by vinyanalista** [comment]
@borkweb said:

> This bug has been fixed in master with the latest upgrade to Boostrap 3!
> 
> I was able to fix this with CSS without creating unnecessary whitespace. Setting the margin and padding to account for the `position: fixed;` elements. [Here's what I did](https://github.com/borkweb/bootstrap-mediawiki/blob/master/style.css#L26) if anyone is curious.

As a matter of fact, it works. I used those CSS lines to fix that same issue on another theme that combines Bootstrap and MediaWiki, [Tweeki](https://github.com/thaider/Tweeki/):

```css
.mw-headline {
	text-shadow: 1px 1px 0 rgb(255,255,255);
}

h2 .mw-headline { font-size: 18px; }
h3 .mw-headline { font-size: 16px; }
h4 .mw-headline { font-size: 14px; }
h5 .mw-headline { font-size: 12px; }
h6 .mw-headline { font-size: 12px; }
```

But, at least for me, I'm not a CSS expert, those lines are the kind of thing that can not be explained, they just work, like magic! XD
